interface Props {
  summary: string;
  docType: string;
  chunked: boolean;
  tokenCount: number;
  latencySeconds: number;
}

const DOC_TYPE_LABELS: Record<string, string> = {
  discharge_summary: "Discharge Summary",
  clinical_note: "Clinical Note",
  research_abstract: "Research Abstract",
  unspecified_medical_document: "Medical Document",
};

export function TechnicalSummaryCard({ summary, docType, chunked, tokenCount, latencySeconds }: Props) {
  return (
    <div className="rounded-md border border-ink-200 bg-white shadow-panel">
      <div className="flex flex-wrap items-center justify-between gap-2 border-b border-ink-100 px-4 py-3">
        <div className="flex items-center gap-2">
          <h3 className="text-[13px] font-semibold uppercase tracking-wide text-ink-600">Technical Summary</h3>
          <span className="rounded border border-ink-200 px-1.5 py-0.5 text-[11px] text-ink-500">
            {DOC_TYPE_LABELS[docType] ?? docType}
          </span>
        </div>
        <span className="font-mono text-[11px] text-ink-400">
          {tokenCount.toLocaleString()} tokens{chunked ? " · chunked" : ""} · {latencySeconds.toFixed(1)}s
        </span>
      </div>
      <div className="px-4 py-3.5">
        <p className="whitespace-pre-wrap text-[14px] leading-relaxed text-ink-800">{summary}</p>
      </div>
      <div className="border-t border-ink-100 bg-ink-50 px-4 py-2">
        <span className="inline-flex items-center gap-1.5 text-[11px] font-medium text-ink-500">
          <span className="inline-block h-1.5 w-1.5 rounded-full bg-ink-400" />
          Generated by a QLoRA fine-tuned model (Phi-3-mini, trained on PubMed abstracts)
        </span>
      </div>
    </div>
  );
}
