import { useState } from "react";
import { Header } from "./components/Header";
import { DisclaimerBanner } from "./components/DisclaimerBanner";
import { DocumentInputPanel } from "./components/DocumentInputPanel";
import { TechnicalSummaryCard } from "./components/TechnicalSummaryCard";
import { PatientExplanationCard } from "./components/PatientExplanationCard";
import { VerificationPanel } from "./components/VerificationPanel";
import { summarizeDocument, ApiRequestError } from "./api";
import type { SummarizeResponse } from "./types";

function App() {
  const [document, setDocument] = useState("");
  const [result, setResult] = useState<SummarizeResponse | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const handleSubmit = async () => {
    setIsLoading(true);
    setError(null);
    try {
      const response = await summarizeDocument(document);
      setResult(response);
    } catch (err) {
      setError(err instanceof ApiRequestError ? err.message : "Something went wrong reaching the summarization service.");
      setResult(null);
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="flex min-h-screen flex-col">
      <Header />
      <DisclaimerBanner />

      <main className="mx-auto w-full max-w-7xl flex-1 px-6 py-6">
        <div className="grid grid-cols-1 gap-5 lg:grid-cols-2">
          <DocumentInputPanel value={document} onChange={setDocument} onSubmit={handleSubmit} isLoading={isLoading} />

          <div className="flex flex-col gap-4">
            {error && (
              <div className="rounded-md border border-critical-100 bg-critical-50 px-4 py-3 text-sm text-critical-700">
                {error}
              </div>
            )}

            {!error && !result && !isLoading && (
              <div className="flex h-full min-h-[320px] flex-col items-center justify-center rounded-md border border-dashed border-ink-200 px-6 text-center text-sm text-ink-400">
                Paste a document and click "Summarize document" to see the technical summary,
                patient-friendly explanation, and entity coverage check here.
              </div>
            )}

            {result && !error && (
              <>
                <TechnicalSummaryCard
                  summary={result.technical_summary}
                  docType={result.doc_type}
                  chunked={result.chunked}
                  tokenCount={result.token_count}
                  latencySeconds={result.latency_seconds}
                />
                <VerificationPanel verification={result.verification} regenerationCount={result.regeneration_count} />
                <PatientExplanationCard explanation={result.patient_explanation} />
              </>
            )}
          </div>
        </div>
      </main>

      <footer className="border-t border-ink-200 px-6 py-4 text-center text-xs text-ink-400">
        Synopsis is a research prototype. Technical summary generated by a QLoRA fine-tuned model; patient
        explanation generated by prompt-based LLM completion. Neither output has been clinically validated.
      </footer>
    </div>
  );
}

export default App;
